import json

from pytr.event import ConditionalEventType, Event, PPEventType
from pytr.transactions import TransactionExporter


def test_events():
    test_data = [
        {
            "filename": "aktien_entfernt.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "DK0064307839",
            "isin2": "ORSTED A/S   -ANR-",
            "title": "ORSTED A/S   -ANR-",
            "shares": 0.285835,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-28T15:46:46",
                    "Gebühren": None,
                    "ISIN": "DK0064307839",
                    "Notiz": "ORSTED A/S   -ANR-",
                    "Steuern": None,
                    "Stück": 0.285835,
                    "Typ": "Verkauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "aktien_entfernt_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "DK0064307839",
            "isin2": "ORSTED A/S   -ANR-",
            "title": "ORSTED A/S   -ANR-",
            "shares": 0.285835,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-28T15:46:46",
                    "Gebühren": None,
                    "ISIN": "DK0064307839",
                    "Notiz": "ORSTED A/S   -ANR-",
                    "Steuern": None,
                    "Stück": 0.285835,
                    "Typ": "Verkauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "aktienbonus.json",
            "event_type": ConditionalEventType.SAVEBACK,
            "isin": "US2546871060",
            "isin2": None,
            "title": "Aktien-Bonus",
            "shares": 0.105,
            "shares2": None,
            "value": -10.03,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-13T14:49:06",
                    "Gebühren": None,
                    "ISIN": "US2546871060",
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": 0.105,
                    "Typ": "Kauf",
                    "Wert": -10.03,
                },
                {
                    "Datum": "2025-10-13T14:49:06",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 10.03,
                },
            ],
        },
        {
            "filename": "aktienbonus_no_eventType.json",
            "event_type": ConditionalEventType.SAVEBACK,
            "isin": "US2546871060",
            "isin2": None,
            "title": "Aktien-Bonus",
            "shares": 0.105,
            "shares2": None,
            "value": -10.03,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-13T14:49:06",
                    "Gebühren": None,
                    "ISIN": "US2546871060",
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": 0.105,
                    "Typ": "Kauf",
                    "Wert": -10.03,
                },
                {
                    "Datum": "2025-10-13T14:49:06",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 10.03,
                },
            ],
        },
        {
            "filename": "aktiendividende.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US2935941078",
            "isin2": "Enovix Corp. WTS 01.10.26",
            "title": "Enovix",
            "shares": 0.494370,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-07-22T14:31:49",
                    "Gebühren": None,
                    "ISIN": "US2935941318",
                    "Notiz": "Enovix Corp. WTS 01.10.26",
                    "Steuern": None,
                    "Stück": 0.494370,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "aktiendividende_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US2935941078",
            "isin2": "Enovix Corp. WTS 01.10.26",
            "title": "Enovix",
            "shares": 0.494370,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-07-22T14:31:49",
                    "Gebühren": None,
                    "ISIN": "US2935941318",
                    "Notiz": "Enovix Corp. WTS 01.10.26",
                    "Steuern": None,
                    "Stück": 0.494370,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "aktienpraemiendividende.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "JE00B4T3BW64",
            "isin2": "Glencore",
            "title": "Glencore",
            "shares": None,
            "shares2": None,
            "value": 3,
            "taxes": -1.15,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-09-22T11:20:31",
                    "Gebühren": None,
                    "ISIN": "JE00B4T3BW64",
                    "Notiz": "Glencore",
                    "Steuern": 1.15,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": 3.0,
                }
            ],
        },
        {
            "filename": "aktienpraemiendividende_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "JE00B4T3BW64",
            "isin2": "Glencore",
            "title": "Glencore",
            "shares": None,
            "shares2": None,
            "value": 3,
            "taxes": -1.15,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-09-22T11:20:31",
                    "Gebühren": None,
                    "ISIN": "JE00B4T3BW64",
                    "Notiz": "Glencore",
                    "Steuern": 1.15,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": 3.0,
                }
            ],
        },
        {
            "filename": "aktiensplit.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US1696561059",
            "isin2": "Chipotle",
            "title": "Chipotle Mexican Grill",
            "shares": 49,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-06-26T08:06:40",
                    "Gebühren": None,
                    "ISIN": "US1696561059",
                    "Notiz": "Chipotle",
                    "Steuern": None,
                    "Stück": 49,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "aktiensplit_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US64110L1061",
            "isin2": "Netflix",
            "title": "Netflix",
            "shares": 2.743902,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-17T06:07:56",
                    "Gebühren": None,
                    "ISIN": "US64110L1061",
                    "Notiz": "Netflix",
                    "Steuern": None,
                    "Stück": 2.743902,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "bardividende.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "US20030N1019",
            "isin2": "Comcast (A)",
            "title": "Comcast (A)",
            "shares": 10.640298,
            "shares2": None,
            "value": 2.24,
            "taxes": -0.78,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-23T14:19:56",
                    "Gebühren": None,
                    "ISIN": "US20030N1019",
                    "Notiz": "Comcast (A)",
                    "Steuern": 0.78,
                    "Stück": 10.640298,
                    "Typ": "Dividende",
                    "Wert": 2.24,
                }
            ],
        },
        {
            "filename": "bardividende_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "US5486611073",
            "isin2": "Lowe's",
            "title": "Lowe's",
            "shares": 1.189904,
            "shares2": None,
            "value": 0.92,
            "taxes": -0.32,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-05T18:31:19",
                    "Gebühren": None,
                    "ISIN": "US5486611073",
                    "Notiz": "Lowe's",
                    "Steuern": 0.32,
                    "Stück": 1.189904,
                    "Typ": "Dividende",
                    "Wert": 0.92,
                }
            ],
        },
        {
            "filename": "bardividende_korrigiert.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "US58463J3041",
            "isin2": "Medical Properties Trust",
            "title": "Medical Properties Trust",
            "shares": 40,
            "shares2": None,
            "value": 4.01,
            "taxes": -1.53,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-03-20T15:04:31",
                    "Gebühren": None,
                    "ISIN": "US58463J3041",
                    "Notiz": "Medical Properties Trust",
                    "Steuern": 1.53,
                    "Stück": 40.0,
                    "Typ": "Dividende",
                    "Wert": 4.01,
                }
            ],
        },
        {
            "filename": "bardividende_korrigiert_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "US58463J3041",
            "isin2": "Medical Properties Trust",
            "title": "Medical Properties Trust",
            "shares": 40,
            "shares2": None,
            "value": 4.01,
            "taxes": -1.53,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-03-20T15:04:31",
                    "Gebühren": None,
                    "ISIN": "US58463J3041",
                    "Notiz": "Medical Properties Trust",
                    "Steuern": 1.53,
                    "Stück": 40.0,
                    "Typ": "Dividende",
                    "Wert": 4.01,
                }
            ],
        },
        {
            "filename": "benefits_spare_change_execution.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "IE00077FRP95",
            "isin2": None,
            "title": "SuperDividend USD (Dist)",
            "shares": 0.383219,
            "shares2": None,
            "value": -3.38,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-10-02T15:05:40",
                    "Gebühren": None,
                    "ISIN": "IE00077FRP95",
                    "Notiz": "SuperDividend USD (Dist)",
                    "Steuern": None,
                    "Stück": 0.383219,
                    "Typ": "Kauf",
                    "Wert": -3.38,
                }
            ],
        },
        {
            "filename": "benefits_spare_change_execution_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "IE00077FRP95",
            "isin2": None,
            "title": "SuperDividend USD (Dist)",
            "shares": 0.383219,
            "shares2": None,
            "value": -3.38,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-10-02T15:05:40",
                    "Gebühren": None,
                    "ISIN": "IE00077FRP95",
                    "Notiz": "SuperDividend USD (Dist)",
                    "Steuern": None,
                    "Stück": 0.383219,
                    "Typ": "Kauf",
                    "Wert": -3.38,
                }
            ],
        },
        {
            "filename": "bonusaktien.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DE0005659700",
            "isin2": "Eckert & Ziegler",
            "title": "Eckert & Ziegler",
            "shares": 5.706536,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-15T08:10:12",
                    "Gebühren": None,
                    "ISIN": "DE0005659700",
                    "Notiz": "Eckert & Ziegler",
                    "Steuern": None,
                    "Stück": 5.706536,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "bonusaktien_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DE0005659700",
            "isin2": "Eckert & Ziegler",
            "title": "Eckert & Ziegler",
            "shares": 5.706536,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-15T08:10:12",
                    "Gebühren": None,
                    "ISIN": "DE0005659700",
                    "Notiz": "Eckert & Ziegler",
                    "Steuern": None,
                    "Stück": 5.706536,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "bonusaktien2.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "CNE100000296",
            "isin2": "BYD",
            "title": "BYD",
            "shares": None,
            "shares2": None,
            "value": -8.67,
            "taxes": -8.67,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-15T14:53:09",
                    "Gebühren": None,
                    "ISIN": "CNE100000296",
                    "Notiz": "BYD",
                    "Steuern": 8.67,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": -8.67,
                }
            ],
        },
        {
            "filename": "bonusaktien2_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "CNE100000296",
            "isin2": "BYD",
            "title": "BYD",
            "shares": None,
            "shares2": None,
            "value": -8.67,
            "taxes": -8.67,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-15T14:53:09",
                    "Gebühren": None,
                    "ISIN": "CNE100000296",
                    "Notiz": "BYD",
                    "Steuern": 8.67,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": -8.67,
                }
            ],
        },
        {
            "filename": "buy.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "IE00B4K6B022",
            "isin2": None,
            "title": "Euro Stoxx 50 EUR (Dist)",
            "shares": 60,
            "shares2": None,
            "value": -3002.8,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-02-20T16:32:07",
                    "Gebühren": -1.0,
                    "ISIN": "IE00B4K6B022",
                    "Notiz": "Euro Stoxx 50 EUR (Dist)",
                    "Steuern": None,
                    "Stück": 60.0,
                    "Typ": "Kauf",
                    "Wert": -3002.8,
                }
            ],
        },
        {
            "filename": "buy_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "IE00B4K6B022",
            "isin2": None,
            "title": "Euro Stoxx 50 EUR (Dist)",
            "shares": 60,
            "shares2": None,
            "value": -3002.8,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-02-20T16:32:07",
                    "Gebühren": -1.0,
                    "ISIN": "IE00B4K6B022",
                    "Notiz": "Euro Stoxx 50 EUR (Dist)",
                    "Steuern": None,
                    "Stück": 60.0,
                    "Typ": "Kauf",
                    "Wert": -3002.8,
                }
            ],
        },
        {
            "filename": "buy_new.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US67066G1040",
            "isin2": None,
            "title": "NVIDIA",
            "shares": 0.685102,
            "shares2": None,
            "value": -111,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-10T19:29:43",
                    "Gebühren": -1.0,
                    "ISIN": "US67066G1040",
                    "Notiz": "NVIDIA",
                    "Steuern": None,
                    "Stück": 0.685102,
                    "Typ": "Kauf",
                    "Wert": -111,
                }
            ],
        },
        {
            "filename": "buy_new_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US67066G1040",
            "isin2": None,
            "title": "NVIDIA",
            "shares": 0.685102,
            "shares2": None,
            "value": -111,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-10T19:29:43",
                    "Gebühren": -1.0,
                    "ISIN": "US67066G1040",
                    "Notiz": "NVIDIA",
                    "Steuern": None,
                    "Stück": 0.685102,
                    "Typ": "Kauf",
                    "Wert": -111,
                }
            ],
        },
        {
            "filename": "buy_new2.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US7731211089",
            "isin2": None,
            "title": "Rocket Lab Corp. Registered Shares DL-,0001",
            "shares": 2,
            "shares2": None,
            "value": -75.6,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-01T08:28:01",
                    "Gebühren": -1.0,
                    "ISIN": "US7731211089",
                    "Notiz": "Rocket Lab Corp. Registered Shares DL-,0001",
                    "Steuern": None,
                    "Stück": 2,
                    "Typ": "Kauf",
                    "Wert": -75.6,
                }
            ],
        },
        {
            "filename": "buy_new2_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US7731211089",
            "isin2": None,
            "title": "Rocket Lab Corp. Registered Shares DL-,0001",
            "shares": 2,
            "shares2": None,
            "value": -75.6,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-01T08:28:01",
                    "Gebühren": -1.0,
                    "ISIN": "US7731211089",
                    "Notiz": "Rocket Lab Corp. Registered Shares DL-,0001",
                    "Steuern": None,
                    "Stück": 2,
                    "Typ": "Kauf",
                    "Wert": -75.6,
                }
            ],
        },
        {
            "filename": "card_refund.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Decathlon",
            "shares": None,
            "shares2": None,
            "value": 24.99,
            "taxes": None,
            "note": "card_refund",
            "transactions": [
                {
                    "Datum": "2025-08-17T07:23:44",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Kartenerstattung - Decathlon",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 24.99,
                }
            ],
        },
        {
            "filename": "card_refund_no_eventType.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Decathlon",
            "shares": None,
            "shares2": None,
            "value": 24.99,
            "taxes": None,
            "note": "card_refund",
            "transactions": [
                {
                    "Datum": "2025-08-17T07:23:44",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Kartenerstattung - Decathlon",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 24.99,
                }
            ],
        },
        {
            "filename": "deposit.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "My Name",
            "shares": None,
            "shares2": None,
            "value": 200,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-06-03T17:07:26",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "My Name",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 200.0,
                }
            ],
        },
        {
            "filename": "deposit_no_eventType.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "My Name",
            "shares": None,
            "shares2": None,
            "value": 200,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-06-03T17:07:26",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "My Name",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 200.0,
                }
            ],
        },
        {
            "filename": "dividende_old.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "LU0392494562",
            "isin2": None,
            "title": "MSCI World USD (Dist)",
            "shares": 32,
            "shares2": None,
            "value": 30.21,
            "taxes": 6.83,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-12-31T23:59:59",
                    "Gebühren": None,
                    "ISIN": "LU0392494562",
                    "Notiz": "MSCI World USD (Dist)",
                    "Steuern": -6.83,
                    "Stück": 32.0,
                    "Typ": "Dividende",
                    "Wert": 30.21,
                }
            ],
        },
        {
            "filename": "dividende_wahlweise.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "GB00BDR05C01",
            "isin2": "National Grid",
            "title": "National Grid",
            "shares": None,
            "shares2": None,
            "value": 3.37,
            "taxes": -1.28,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-07-19T13:28:04",
                    "Gebühren": None,
                    "ISIN": "GB00BDR05C01",
                    "Notiz": "National Grid",
                    "Steuern": 1.28,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": 3.37,
                }
            ],
        },
        {
            "filename": "dividende_wahlweise_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "GB00BDR05C01",
            "isin2": "National Grid",
            "title": "National Grid",
            "shares": None,
            "shares2": None,
            "value": 3.37,
            "taxes": -1.28,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-07-19T13:28:04",
                    "Gebühren": None,
                    "ISIN": "GB00BDR05C01",
                    "Notiz": "National Grid",
                    "Steuern": 1.28,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": 3.37,
                }
            ],
        },
        {
            "filename": "incoming_transfer.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Klaus Mustermann",
            "shares": None,
            "shares2": None,
            "value": 88.04,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-09-02T17:49:12",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Klaus Mustermann",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 88.04,
                }
            ],
        },
        {
            "filename": "incoming_transfer_no_eventType.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Klaus Mustermann",
            "shares": None,
            "shares2": None,
            "value": 88.04,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-09-02T17:49:12",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Klaus Mustermann",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 88.04,
                }
            ],
        },
        {
            "filename": "incoming_transfer_delegation.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Vorname Nachname",
            "shares": None,
            "shares2": None,
            "value": 3000.0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-09-10T13:18:31",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Vorname Nachname",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 3000.0,
                }
            ],
        },
        {
            "filename": "incoming_transfer_delegation_no_eventType.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Vorname Nachname",
            "shares": None,
            "shares2": None,
            "value": 3000.0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-09-10T13:18:31",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Vorname Nachname",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 3000.0,
                }
            ],
        },
        {
            "filename": "junior_p2p_transfer.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Maria Mueller",
            "shares": None,
            "shares2": None,
            "value": -50,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-09-17T19:35:32",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Maria Mueller",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -50.0,
                }
            ],
        },
        {
            "filename": "junior_p2p_transfer_no_eventType.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Maria Mueller",
            "shares": None,
            "shares2": None,
            "value": -50,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-09-17T19:35:32",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Maria Mueller",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -50.0,
                }
            ],
        },
        {
            "filename": "kartenzahlung.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Coop Pronto",
            "shares": None,
            "shares2": None,
            "value": -12.16,
            "taxes": None,
            "note": "card_successful_transaction",
            "transactions": [
                {
                    "Datum": "2025-10-21T17:30:01",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Kartentransaktion - Coop Pronto",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -12.16,
                }
            ],
        },
        {
            "filename": "kartenzahlung_no_eventType.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Baecker",
            "shares": None,
            "shares2": None,
            "value": -2,
            "taxes": None,
            "note": "card_successful_transaction",
            "transactions": [
                {
                    "Datum": "2025-11-05T11:00:07",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Kartentransaktion - Baecker",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -2.0,
                }
            ],
        },
        {
            "filename": "legacy_verkauforder_neu_abgerechnet.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "FR0000060873",
            "isin2": None,
            "title": "Marie Brizard Wine and Spirits",
            "shares": 27,
            "shares2": None,
            "value": 91.34,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-02-21T11:14:54",
                    "Gebühren": -1.0,
                    "ISIN": "FR0000060873",
                    "Notiz": "Marie Brizard Wine and Spirits",
                    "Steuern": None,
                    "Stück": 27.0,
                    "Typ": "Verkauf",
                    "Wert": 91.34,
                }
            ],
        },
        {
            "filename": "legacy_verkauforder_neu_abgerechnet_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "FR0000060873",
            "isin2": None,
            "title": "Marie Brizard Wine and Spirits",
            "shares": 27,
            "shares2": None,
            "value": 91.34,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-02-21T11:14:54",
                    "Gebühren": -1.0,
                    "ISIN": "FR0000060873",
                    "Notiz": "Marie Brizard Wine and Spirits",
                    "Steuern": None,
                    "Stück": 27.0,
                    "Typ": "Verkauf",
                    "Wert": 91.34,
                }
            ],
        },
        {
            "filename": "legacy_zinsen.json",
            "event_type": PPEventType.INTEREST,
            "isin": None,
            "isin2": None,
            "title": "Zinsen",
            "shares": None,
            "shares2": None,
            "value": 11.76,
            "taxes": 4.51,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-09-01T16:39:48",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Zinsen",
                    "Steuern": -4.51,
                    "Stück": None,
                    "Typ": "Zinsen",
                    "Wert": 11.76,
                }
            ],
        },
        {
            "filename": "legacy_zinsen_no_eventType.json",
            "event_type": PPEventType.INTEREST,
            "isin": None,
            "isin2": None,
            "title": "Zinsen",
            "shares": None,
            "shares2": None,
            "value": 11.76,
            "taxes": 4.51,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-09-01T16:39:48",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Zinsen",
                    "Steuern": -4.51,
                    "Stück": None,
                    "Typ": "Zinsen",
                    "Wert": 11.76,
                }
            ],
        },
        {
            "filename": "limit-sell-order.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US26740W1099",
            "isin2": None,
            "title": "D-Wave Quantum",
            "shares": 11,
            "shares2": None,
            "value": 114.91,
            "taxes": 17.36,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-05-20T08:03:45",
                    "Gebühren": -1.0,
                    "ISIN": "US26740W1099",
                    "Notiz": "D-Wave Quantum",
                    "Steuern": -17.36,
                    "Stück": 11.0,
                    "Typ": "Verkauf",
                    "Wert": 114.91,
                }
            ],
        },
        {
            "filename": "limit-sell-order_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US8816242098",
            "isin2": None,
            "title": "Teva Pharmaceutical Industries (ADR)",
            "shares": 8,
            "shares2": None,
            "value": 139.74,
            "taxes": 7.66,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-05T12:03:19",
                    "Gebühren": -1.0,
                    "ISIN": "US8816242098",
                    "Notiz": "Teva Pharmaceutical Industries (ADR)",
                    "Steuern": -7.66,
                    "Stück": 8.0,
                    "Typ": "Verkauf",
                    "Wert": 139.74,
                }
            ],
        },
        {
            "filename": "limit-sell-order_old.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "DE000DTR0CK8",
            "isin2": None,
            "title": "Daimler Truck Holding",
            "shares": 3,
            "shares2": None,
            "value": 119.37,
            "taxes": 0.14,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-05-14T07:01:32",
                    "Gebühren": -1.0,
                    "ISIN": "DE000DTR0CK8",
                    "Notiz": "Daimler Truck Holding",
                    "Steuern": -0.14,
                    "Stück": 3.0,
                    "Typ": "Verkauf",
                    "Wert": 119.37,
                }
            ],
        },
        {
            "filename": "limit-sell-order_old_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "DE000DTR0CK8",
            "isin2": None,
            "title": "Daimler Truck Holding",
            "shares": 3,
            "shares2": None,
            "value": 119.37,
            "taxes": 0.14,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-05-14T07:01:32",
                    "Gebühren": -1.0,
                    "ISIN": "DE000DTR0CK8",
                    "Notiz": "Daimler Truck Holding",
                    "Steuern": -0.14,
                    "Stück": 3.0,
                    "Typ": "Verkauf",
                    "Wert": 119.37,
                }
            ],
        },
        {
            "filename": "outgoing_transfer.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Hans Mustermann",
            "shares": None,
            "shares2": None,
            "value": -50.3,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-07-21T09:35:47",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Hans Mustermann",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -50.3,
                }
            ],
        },
        {
            "filename": "outgoing_transfer_no_eventType.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Hans Mustermann",
            "shares": None,
            "shares2": None,
            "value": -50.3,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2024-07-21T09:35:47",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Hans Mustermann",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -50.3,
                }
            ],
        },
        {
            "filename": "outgoing_transfer_delegation.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Nina",
            "shares": None,
            "shares2": None,
            "value": -67,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-18T12:16:06",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Nina",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -67.0,
                }
            ],
        },
        {
            "filename": "outgoing_transfer_delegation_no_eventType.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "Nina",
            "shares": None,
            "shares2": None,
            "value": -67,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-08-18T12:16:06",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Nina",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -67.0,
                }
            ],
        },
        {
            "filename": "outgoing_transfer_legacy.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "My Name",
            "shares": None,
            "shares2": None,
            "value": -750,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-04-11T06:44:43",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "My Name",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -750.0,
                }
            ],
        },
        {
            "filename": "outgoing_transfer_legacy_no_eventType.json",
            "event_type": PPEventType.REMOVAL,
            "isin": None,
            "isin2": None,
            "title": "My Name",
            "shares": None,
            "shares2": None,
            "value": -750,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-04-11T06:44:43",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "My Name",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Entnahme",
                    "Wert": -750.0,
                }
            ],
        },
        {
            "filename": "payment_inbound_credit_card.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Einzahlung",
            "shares": None,
            "shares2": None,
            "value": 1000,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2022-08-27T05:06:30",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Einzahlung",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 1000.0,
                }
            ],
        },
        {
            "filename": "payment_inbound_credit_card_no_eventType.json",
            "event_type": PPEventType.DEPOSIT,
            "isin": None,
            "isin2": None,
            "title": "Einzahlung",
            "shares": None,
            "shares2": None,
            "value": 1000,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2022-08-27T05:06:30",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Einzahlung",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 1000.0,
                }
            ],
        },
        {
            "filename": "private_markets_order.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3176111881",
            "isin2": None,
            "title": "Private Equity",
            "shares": 1,
            "shares2": None,
            "value": -101,
            "taxes": None,
            "note": "Kauforder",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:15:25",
                    "Typ": "Kauf",
                    "Wert": -101.0,
                    "Notiz": "EQT",
                    "ISIN": "LU3176111881",
                    "Stück": 1.0,
                    "Gebühren": -1.0,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_order_no_eventType.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3176111881",
            "isin2": None,
            "title": "Private Equity",
            "shares": 1,
            "shares2": None,
            "value": -101,
            "taxes": None,
            "note": "Kauforder",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:15:25",
                    "Typ": "Kauf",
                    "Wert": -101.0,
                    "Notiz": "EQT",
                    "ISIN": "LU3176111881",
                    "Stück": 1.0,
                    "Gebühren": -1.0,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_order_bonus.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3176111881",
            "isin2": None,
            "title": "Private Equity",
            "shares": 0.01,
            "shares2": None,
            "value": -1,
            "taxes": None,
            "note": "1 % Bonus",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:15:25",
                    "Typ": "Kauf",
                    "Wert": -1.0,
                    "Notiz": "EQT",
                    "ISIN": "LU3176111881",
                    "Stück": 0.01,
                    "Gebühren": None,
                    "Steuern": None,
                },
                {
                    "Datum": "2025-09-18T07:15:25",
                    "Typ": "Einlage",
                    "Wert": 1.0,
                    "Notiz": "EQT",
                    "ISIN": None,
                    "Stück": None,
                    "Gebühren": None,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_order_bonus_no_eventType.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3176111881",
            "isin2": None,
            "title": "Private Equity",
            "shares": 0.01,
            "shares2": None,
            "value": -1,
            "taxes": None,
            "note": "1 % Bonus",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:15:25",
                    "Typ": "Kauf",
                    "Wert": -1.0,
                    "Notiz": "EQT",
                    "ISIN": "LU3176111881",
                    "Stück": 0.01,
                    "Gebühren": None,
                    "Steuern": None,
                },
                {
                    "Datum": "2025-09-18T07:15:25",
                    "Typ": "Einlage",
                    "Wert": 1.0,
                    "Notiz": "EQT",
                    "ISIN": None,
                    "Stück": None,
                    "Gebühren": None,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_trade.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3170240538",
            "isin2": None,
            "title": "Private Equity",
            "shares": 1,
            "shares2": None,
            "value": -101,
            "taxes": None,
            "note": "Kauforder",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:14:56",
                    "Typ": "Kauf",
                    "Wert": -101.0,
                    "Notiz": "Apollo",
                    "ISIN": "LU3170240538",
                    "Stück": 1.0,
                    "Gebühren": -1.0,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_trade_no_eventType.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3170240538",
            "isin2": None,
            "title": "Private Equity",
            "shares": 1,
            "shares2": None,
            "value": -101,
            "taxes": None,
            "note": "Kauforder",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:14:56",
                    "Typ": "Kauf",
                    "Wert": -101.0,
                    "Notiz": "Apollo",
                    "ISIN": "LU3170240538",
                    "Stück": 1.0,
                    "Gebühren": -1.0,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_trade_bonus.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3170240538",
            "isin2": None,
            "title": "Private Equity",
            "shares": 0.01,
            "shares2": None,
            "value": -1,
            "taxes": None,
            "note": "1 % Bonus",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:14:56",
                    "Typ": "Kauf",
                    "Wert": -1,
                    "Notiz": "Apollo",
                    "ISIN": "LU3170240538",
                    "Stück": 0.01,
                    "Gebühren": None,
                    "Steuern": None,
                },
                {
                    "Datum": "2025-09-18T07:14:56",
                    "Typ": "Einlage",
                    "Wert": 1,
                    "Notiz": "Apollo",
                    "ISIN": None,
                    "Stück": None,
                    "Gebühren": None,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "private_markets_trade_bonus_no_eventType.json",
            "event_type": ConditionalEventType.PRIVATE_MARKETS_ORDER,
            "isin": "LU3170240538",
            "isin2": None,
            "title": "Private Equity",
            "shares": 0.01,
            "shares2": None,
            "value": -1,
            "taxes": None,
            "note": "1 % Bonus",
            "transactions": [
                {
                    "Datum": "2025-09-18T07:14:56",
                    "Typ": "Kauf",
                    "Wert": -1,
                    "Notiz": "Apollo",
                    "ISIN": "LU3170240538",
                    "Stück": 0.01,
                    "Gebühren": None,
                    "Steuern": None,
                },
                {
                    "Datum": "2025-09-18T07:14:56",
                    "Typ": "Einlage",
                    "Wert": 1,
                    "Notiz": "Apollo",
                    "ISIN": None,
                    "Stück": None,
                    "Gebühren": None,
                    "Steuern": None,
                },
            ],
        },
        {
            "filename": "reverse_split.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US3789734080",
            "isin2": "GLOBALSTAR INC. O.N.",
            "title": "Globalstar",
            "shares": 110.403067,
            "shares2": 7.360204,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-02-11T08:13:48",
                    "Gebühren": None,
                    "ISIN": "US3789734080",
                    "Notiz": "Globalstar",
                    "Steuern": None,
                    "Stück": 110.403067,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
                {
                    "Datum": "2025-02-11T08:13:48",
                    "Gebühren": None,
                    "ISIN": "US3789735079",
                    "Notiz": "GLOBALSTAR INC. O.N.",
                    "Steuern": None,
                    "Stück": 7.360204,
                    "Typ": "Kauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "reverse_split_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US3789734080",
            "isin2": "GLOBALSTAR INC. O.N.",
            "title": "Globalstar",
            "shares": 110.403067,
            "shares2": 7.360204,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-02-11T08:13:48",
                    "Gebühren": None,
                    "ISIN": "US3789734080",
                    "Notiz": "Globalstar",
                    "Steuern": None,
                    "Stück": 110.403067,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
                {
                    "Datum": "2025-02-11T08:13:48",
                    "Gebühren": None,
                    "ISIN": "US3789735079",
                    "Notiz": "GLOBALSTAR INC. O.N.",
                    "Steuern": None,
                    "Stück": 7.360204,
                    "Typ": "Kauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "saveback.json",
            "event_type": ConditionalEventType.SAVEBACK,
            "isin": "IE00B3WJKG14",
            "isin2": None,
            "title": "S&P 500 Information Tech USD (Acc)",
            "shares": 0.546348,
            "shares2": None,
            "value": -15,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-04-02T13:54:23",
                    "Gebühren": None,
                    "ISIN": "IE00B3WJKG14",
                    "Notiz": "S&P 500 Information Tech USD (Acc)",
                    "Steuern": None,
                    "Stück": 0.546348,
                    "Typ": "Kauf",
                    "Wert": -15.0,
                },
                {
                    "Datum": "2025-04-02T13:54:23",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "S&P 500 Information Tech USD (Acc)",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 15.0,
                },
            ],
        },
        {
            "filename": "saveback_no_eventType.json",
            "event_type": ConditionalEventType.SAVEBACK,
            "isin": "US5398301094",
            "isin2": None,
            "title": "Lockheed Martin",
            "shares": 0.035252,
            "shares2": None,
            "value": -15,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-03T15:30:22",
                    "Gebühren": None,
                    "ISIN": "US5398301094",
                    "Notiz": "Lockheed Martin",
                    "Steuern": None,
                    "Stück": 0.035252,
                    "Typ": "Kauf",
                    "Wert": -15.0,
                },
                {
                    "Datum": "2025-11-03T15:30:22",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Lockheed Martin",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 15.0,
                },
            ],
        },
        {
            "filename": "savingsplan.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "AU000000DRO2",
            "isin2": None,
            "title": "DroneShield",
            "shares": 6.921675,
            "shares2": None,
            "value": -19,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-23T08:26:13",
                    "Gebühren": None,
                    "ISIN": "AU000000DRO2",
                    "Notiz": "DroneShield",
                    "Steuern": None,
                    "Stück": 6.921675,
                    "Typ": "Kauf",
                    "Wert": -19.0,
                }
            ],
        },
        {
            "filename": "savingsplan_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US8740391003",
            "isin2": None,
            "title": "TSMC (ADR)",
            "shares": 0.037523,
            "shares2": None,
            "value": -10,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-03T15:58:11",
                    "Gebühren": None,
                    "ISIN": "US8740391003",
                    "Notiz": "TSMC (ADR)",
                    "Steuern": None,
                    "Stück": 0.037523,
                    "Typ": "Kauf",
                    "Wert": -10.0,
                }
            ],
        },
        {
            "filename": "sell_stop.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US26740W1099",
            "isin2": None,
            "title": "D-Wave Quantum",
            "shares": 17,
            "shares2": None,
            "value": 94.76,
            "taxes": 3.18,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-03-14T07:03:14",
                    "Gebühren": -1.0,
                    "ISIN": "US26740W1099",
                    "Notiz": "D-Wave Quantum",
                    "Steuern": -3.18,
                    "Stück": 17.0,
                    "Typ": "Verkauf",
                    "Wert": 94.76,
                }
            ],
        },
        {
            "filename": "sell_stop_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US26740W1099",
            "isin2": None,
            "title": "D-Wave Quantum",
            "shares": 17,
            "shares2": None,
            "value": 94.76,
            "taxes": 3.18,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-03-14T07:03:14",
                    "Gebühren": -1.0,
                    "ISIN": "US26740W1099",
                    "Notiz": "D-Wave Quantum",
                    "Steuern": -3.18,
                    "Stück": 17.0,
                    "Typ": "Verkauf",
                    "Wert": 94.76,
                }
            ],
        },
        {
            "filename": "spinoff.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DE0007500001",
            "isin2": "TKMS",
            "title": "ThyssenKrupp",
            "shares": 0.309986,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-20T11:25:29",
                    "Gebühren": None,
                    "ISIN": "DE000TKMS001",
                    "Notiz": "TKMS",
                    "Steuern": None,
                    "Stück": 0.309986,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "spinoff_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DE0007500001",
            "isin2": "TKMS",
            "title": "ThyssenKrupp",
            "shares": 0.309986,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-20T11:25:29",
                    "Gebühren": None,
                    "ISIN": "DE000TKMS001",
                    "Notiz": "TKMS",
                    "Steuern": None,
                    "Stück": 0.309986,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "steuerkorrektur.json",
            "event_type": PPEventType.TAX_REFUND,
            "isin": None,
            "isin2": None,
            "title": "Steuerkorrektur",
            "shares": None,
            "shares2": None,
            "value": 2.87,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-28T00:00:16",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Steuerkorrektur",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Steuerrückerstattung",
                    "Wert": 2.87,
                }
            ],
        },
        {
            "filename": "steuerkorrektur_no_eventType.json",
            "event_type": PPEventType.TAX_REFUND,
            "isin": None,
            "isin2": None,
            "title": "Steuerkorrektur",
            "shares": None,
            "shares2": None,
            "value": 0.76,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-04T23:31:58",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Steuerkorrektur",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Steuerrückerstattung",
                    "Wert": 0.76,
                }
            ],
        },
        {
            "filename": "tausch_no_eventType.json",
            "event_type": None,
            "isin": None,
            "isin2": None,
            "title": "L'Oreal",
            "shares": None,
            "shares2": None,
            "value": None,
            "taxes": None,
            "note": None,
            "transactions": [],
        },
        {
            "filename": "teilrueckzahlung.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DK0064307755",
            "isin2": "Orsted",
            "title": "ORSTED A/S EM.09/25 DK 10",
            "shares": 17,
            "shares2": 17,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-23T14:46:49",
                    "Gebühren": None,
                    "ISIN": "DK0064307755",
                    "Notiz": "ORSTED A/S EM.09/25 DK 10",
                    "Steuern": None,
                    "Stück": 17.0,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
                {
                    "Datum": "2025-10-23T14:46:49",
                    "Gebühren": None,
                    "ISIN": "DK0060094928",
                    "Notiz": "Orsted",
                    "Steuern": None,
                    "Stück": 17.0,
                    "Typ": "Kauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "teilrueckzahlung_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DK0064307755",
            "isin2": "Orsted",
            "title": "ORSTED A/S EM.09/25 DK 10",
            "shares": 17,
            "shares2": 17,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-23T14:46:49",
                    "Gebühren": None,
                    "ISIN": "DK0064307755",
                    "Notiz": "ORSTED A/S EM.09/25 DK 10",
                    "Steuern": None,
                    "Stück": 17.0,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
                {
                    "Datum": "2025-10-23T14:46:49",
                    "Gebühren": None,
                    "ISIN": "DK0060094928",
                    "Notiz": "Orsted",
                    "Steuern": None,
                    "Stück": 17.0,
                    "Typ": "Kauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "tilgung.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "DE000SX12345",
            "isin2": "Long @1,2345",
            "title": "Long 1,2345 $",
            "shares": 100,
            "shares2": None,
            "value": 0.1,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-01-10T10:00:00",
                    "Gebühren": None,
                    "ISIN": "DE000SX12345",
                    "Notiz": "Long 1,2345 $",
                    "Steuern": None,
                    "Stück": 100.0,
                    "Typ": "Dividende",
                    "Wert": 0.1,
                }
            ],
        },
        {
            "filename": "tilgung_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "DE000SX12345",
            "isin2": "Long @1,2345",
            "title": "Long 1,2345 $",
            "shares": 100,
            "shares2": None,
            "value": 0.1,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-01-10T10:00:00",
                    "Gebühren": None,
                    "ISIN": "DE000SX12345",
                    "Notiz": "Long 1,2345 $",
                    "Steuern": None,
                    "Stück": 100.0,
                    "Typ": "Dividende",
                    "Wert": 0.1,
                }
            ],
        },
        {
            "filename": "trade_perk.json",
            "event_type": ConditionalEventType.SAVEBACK,
            "isin": "US0378331005",
            "isin2": None,
            "title": "Aktien-Bonus",
            "shares": 0.0487,
            "shares2": None,
            "value": -10.03,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-04-01T14:09:45",
                    "Gebühren": None,
                    "ISIN": "US0378331005",
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": 0.0487,
                    "Typ": "Kauf",
                    "Wert": -10.03,
                },
                {
                    "Datum": "2025-04-01T14:09:45",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 10.03,
                },
            ],
        },
        {
            "filename": "trade_perk_no_eventType.json",
            "event_type": ConditionalEventType.SAVEBACK,
            "isin": "US0378331005",
            "isin2": None,
            "title": "Aktien-Bonus",
            "shares": 0.0487,
            "shares2": None,
            "value": -10.03,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-04-01T14:09:45",
                    "Gebühren": None,
                    "ISIN": "US0378331005",
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": 0.0487,
                    "Typ": "Kauf",
                    "Wert": -10.03,
                },
                {
                    "Datum": "2025-04-01T14:09:45",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Aktien-Bonus",
                    "Steuern": None,
                    "Stück": None,
                    "Typ": "Einlage",
                    "Wert": 10.03,
                },
            ],
        },
        {
            "filename": "verkaufsorder.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US88032Q1094",
            "isin2": None,
            "title": "Tencent Holdings (ADR)",
            "shares": 3.454506,
            "shares2": None,
            "value": 200.93,
            "taxes": 0.16,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-05-12T18:38:36",
                    "Gebühren": -1.0,
                    "ISIN": "US88032Q1094",
                    "Notiz": "Tencent Holdings (ADR)",
                    "Steuern": -0.16,
                    "Stück": 3.454506,
                    "Typ": "Verkauf",
                    "Wert": 200.93,
                }
            ],
        },
        {
            "filename": "verkaufsorder_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "US4370761029",
            "isin2": None,
            "title": "Home Depot",
            "shares": 0.305182,
            "shares2": None,
            "value": 100,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-11-04T16:27:25",
                    "Gebühren": -1.0,
                    "ISIN": "US4370761029",
                    "Notiz": "Home Depot",
                    "Steuern": None,
                    "Stück": 0.305182,
                    "Typ": "Verkauf",
                    "Wert": 100.0,
                }
            ],
        },
        {
            "filename": "vorabpauschale.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "IE00BJ5JPG56",
            "isin2": "MSCI China USD (Acc)",
            "title": "MSCI China USD (Acc)",
            "shares": None,
            "shares2": None,
            "value": -0.19,
            "taxes": -0.19,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-01-28T14:54:28",
                    "Gebühren": None,
                    "ISIN": "IE00BJ5JPG56",
                    "Notiz": "MSCI China USD (Acc)",
                    "Steuern": 0.19,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": -0.19,
                }
            ],
        },
        {
            "filename": "vorabpauschale_no_eventType.json",
            "event_type": PPEventType.DIVIDEND,
            "isin": "IE00BJ5JPG56",
            "isin2": "MSCI China USD (Acc)",
            "title": "MSCI China USD (Acc)",
            "shares": None,
            "shares2": None,
            "value": -0.19,
            "taxes": -0.19,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-01-28T14:54:28",
                    "Gebühren": None,
                    "ISIN": "IE00BJ5JPG56",
                    "Notiz": "MSCI China USD (Acc)",
                    "Steuern": 0.19,
                    "Stück": None,
                    "Typ": "Dividende",
                    "Wert": -0.19,
                }
            ],
        },
        {
            "filename": "zinsen.json",
            "event_type": PPEventType.INTEREST,
            "isin": None,
            "isin2": None,
            "title": "Zinsen",
            "shares": None,
            "shares2": None,
            "value": 4.87,
            "taxes": 1.87,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-07-01T06:46:37",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Zinsen",
                    "Steuern": -1.87,
                    "Stück": None,
                    "Typ": "Zinsen",
                    "Wert": 4.87,
                }
            ],
        },
        {
            "filename": "zinsen_no_eventType.json",
            "event_type": PPEventType.INTEREST,
            "isin": None,
            "isin2": None,
            "title": "Zinsen",
            "shares": None,
            "shares2": None,
            "value": 4.87,
            "taxes": 1.87,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-07-01T06:46:37",
                    "Gebühren": None,
                    "ISIN": None,
                    "Notiz": "Zinsen",
                    "Steuern": -1.87,
                    "Stück": None,
                    "Typ": "Zinsen",
                    "Wert": 4.87,
                }
            ],
        },
        {
            "filename": "zusammenschluss.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US7731221062",
            "isin2": "ROCKET LAB CORP. O.N.",
            "title": "Rocket Lab USA",
            "shares": 5.943100,
            "shares2": 5.943100,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-05-29T13:04:58",
                    "Gebühren": None,
                    "ISIN": "US7731221062",
                    "Notiz": "Rocket Lab USA",
                    "Steuern": None,
                    "Stück": 5.9431,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
                {
                    "Datum": "2025-05-29T13:04:58",
                    "Gebühren": None,
                    "ISIN": "US7731211089",
                    "Notiz": "ROCKET LAB CORP. O.N.",
                    "Steuern": None,
                    "Stück": 5.9431,
                    "Typ": "Kauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "zusammenschluss_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "US7731221062",
            "isin2": "ROCKET LAB CORP. O.N.",
            "title": "Rocket Lab USA",
            "shares": 5.943100,
            "shares2": 5.943100,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-05-29T13:04:58",
                    "Gebühren": None,
                    "ISIN": "US7731221062",
                    "Notiz": "Rocket Lab USA",
                    "Steuern": None,
                    "Stück": 5.9431,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
                {
                    "Datum": "2025-05-29T13:04:58",
                    "Gebühren": None,
                    "ISIN": "US7731211089",
                    "Notiz": "ROCKET LAB CORP. O.N.",
                    "Steuern": None,
                    "Stück": 5.9431,
                    "Typ": "Kauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "zwischenpapiere.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "DK0064307839",
            "isin2": "ORSTED A/S EM.09/25 DK 10",
            "title": "ORSTED A/S   -ANR-",
            "shares": 119,
            "shares2": 17,
            "value": -151.59,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-21T07:39:39",
                    "Gebühren": None,
                    "ISIN": "DK0064307755",
                    "Notiz": "ORSTED A/S EM.09/25 DK 10",
                    "Steuern": None,
                    "Stück": 17.0,
                    "Typ": "Kauf",
                    "Wert": -151.59,
                },
                {
                    "Datum": "2025-10-21T07:39:39",
                    "Gebühren": None,
                    "ISIN": "DK0064307839",
                    "Notiz": "ORSTED A/S   -ANR-",
                    "Steuern": None,
                    "Stück": 119.0,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "zwischenpapiere_no_eventType.json",
            "event_type": ConditionalEventType.TRADE_INVOICE,
            "isin": "DK0064307839",
            "isin2": "ORSTED A/S EM.09/25 DK 10",
            "title": "ORSTED A/S   -ANR-",
            "shares": 119,
            "shares2": 17,
            "value": -151.59,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-10-21T07:39:39",
                    "Gebühren": None,
                    "ISIN": "DK0064307755",
                    "Notiz": "ORSTED A/S EM.09/25 DK 10",
                    "Steuern": None,
                    "Stück": 17.0,
                    "Typ": "Kauf",
                    "Wert": -151.59,
                },
                {
                    "Datum": "2025-10-21T07:39:39",
                    "Gebühren": None,
                    "ISIN": "DK0064307839",
                    "Notiz": "ORSTED A/S   -ANR-",
                    "Steuern": None,
                    "Stück": 119.0,
                    "Typ": "Verkauf",
                    "Wert": 0,
                },
            ],
        },
        {
            "filename": "zwischenvertrieb.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DK0060094928",
            "isin2": "ORSTED A/S   -ANR-",
            "title": "Orsted",
            "shares": 119.285835,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-09-19T12:02:49",
                    "Gebühren": None,
                    "ISIN": "DK0064307839",
                    "Notiz": "ORSTED A/S   -ANR-",
                    "Steuern": None,
                    "Stück": 119.285835,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
        {
            "filename": "zwischenvertrieb_no_eventType.json",
            "event_type": ConditionalEventType.SPINOFF,
            "isin": "DK0060094928",
            "isin2": "ORSTED A/S   -ANR-",
            "title": "Orsted",
            "shares": 119.285835,
            "shares2": None,
            "value": 0,
            "taxes": None,
            "note": None,
            "transactions": [
                {
                    "Datum": "2025-09-19T12:02:49",
                    "Gebühren": None,
                    "ISIN": "DK0064307839",
                    "Notiz": "ORSTED A/S   -ANR-",
                    "Steuern": None,
                    "Stück": 119.285835,
                    "Typ": "Kauf",
                    "Wert": 0,
                }
            ],
        },
    ]

    # Create an instance of EventCsvFormatter
    formatter = TransactionExporter(lang="de")

    for row in test_data:
        # Load the sample JSON file
        with open("tests/" + row["filename"], "r", encoding="utf-8") as file:
            sample_data = json.load(file)

        # Parse the JSON data using the from_dict function
        event = Event.from_dict(sample_data)

        # Assert the expected values
        assert event.event_type == row["event_type"]
        assert event.isin == row["isin"]
        assert event.isin2 == row["isin2"]
        assert event.title == row["title"]
        assert event.shares == row["shares"]
        assert event.shares2 == row["shares2"]
        assert event.value == row["value"]
        assert event.taxes == row["taxes"]
        assert event.note == row["note"]

        # Format the event to CSV
        transactions = list(formatter.from_event(event))

        # Assert that the output is not an empty string
        assert transactions == row["transactions"]
