name: CI

on:
  - push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          pip install black
      - run: |
          black ./pytr --check

  unittest:
    name: Unit test pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          pip install pytest
      - run: |
          pytest ./tests
